const PROJECT_CURRENCY_VI = 0;
const PROJECT_CURRENCY_EN = 1;
const PROJECT_CURRENCY_KR = 2;

const ProjectCurrencyEnum = {
  [PROJECT_CURRENCY_VI]: PROJECT_CURRENCY_VI,
  [PROJECT_CURRENCY_EN]: PROJECT_CURRENCY_EN,
  [PROJECT_CURRENCY_KR]: PROJECT_CURRENCY_KR,
};

const ProjectCurrencyEnumArr = [
  PROJECT_CURRENCY_VI,
  PROJECT_CURRENCY_EN,
  PROJECT_CURRENCY_KR,
];

export default ProjectCurrencyEnumArr;

export { PROJECT_CURRENCY_VI, PROJECT_CURRENCY_EN, PROJECT_CURRENCY_KR };
