const MILESTONE_STATUS_PENDING = 0
const MILESTONE_STATUS_INPROGRESS = 1
const MILESTONE_STATUS_REVIEW = 2
const MILESTONE_STATUS_COMPLETED = 3
const MILESTONE_STATUS_ONLEAVE = 4
const MILESTONE_STATUS_CANCELLED = 5
const MILESTONE_STATUS_DELETED = 6

const MilestoneStatusEnum = {
    [MILESTONE_STATUS_PENDING]: MILESTONE_STATUS_PENDING,
    [MILESTONE_STATUS_INPROGRESS]: MILESTONE_STATUS_INPROGRESS,
    [MILESTONE_STATUS_REVIEW]: MILESTONE_STATUS_REVIEW,
    [MILESTONE_STATUS_COMPLETED]: MILESTONE_STATUS_COMPLETED,
    [MILESTONE_STATUS_ONLEAVE]: MILESTONE_STATUS_ONLEAVE,
    [MILESTONE_STATUS_CANCELLED]: MILESTONE_STATUS_CANCELLED,
    [MILESTONE_STATUS_DELETED]: MILESTONE_STATUS_DELETED,
}

const MilestoneStatusEnumArr = [
    MILESTONE_STATUS_PENDING,
    MILESTONE_STATUS_INPROGRESS,
    MILESTONE_STATUS_REVIEW,
    MILESTONE_STATUS_COMPLETED,
    MILESTONE_STATUS_ONLEAVE,
    MILESTONE_STATUS_CANCELLED,
    MILESTONE_STATUS_DELETED
]

export default MilestoneStatusEnumArr

export {
    MILESTONE_STATUS_PENDING,
    MILESTONE_STATUS_INPROGRESS,
    MILESTONE_STATUS_REVIEW,
    MILESTONE_STATUS_COMPLETED,
    MILESTONE_STATUS_ONLEAVE,
    MILESTONE_STATUS_CANCELLED,
    MILESTONE_STATUS_DELETED,
}