const TASK_STATUS_PENDING = 0
const TASK_STATUS_INPROGRESS = 1
const TASK_STATUS_REVIEW = 2
const TASK_STATUS_COMPLETED = 3
const TASK_STATUS_ONLEAVE = 4
const TASK_STATUS_CANCELLED = 5
const TASK_STATUS_DELETED = 6

const TaskStatusEnum = {
    [TASK_STATUS_PENDING]: TASK_STATUS_PENDING,
    [TASK_STATUS_INPROGRESS]: TASK_STATUS_INPROGRESS,
    [TASK_STATUS_REVIEW]: TASK_STATUS_REVIEW,
    [TASK_STATUS_COMPLETED]: TASK_STATUS_COMPLETED,
    [TASK_STATUS_ONLEAVE]: TASK_STATUS_ONLEAVE,
    [TASK_STATUS_CANCELLED]: TASK_STATUS_CANCELLED,
    [TASK_STATUS_DELETED]: TASK_STATUS_DELETED,
}

const TaskStatusEnumArr = [
    TASK_STATUS_PENDING,
    TASK_STATUS_INPROGRESS,
    TASK_STATUS_REVIEW,
    TASK_STATUS_COMPLETED,
    TASK_STATUS_ONLEAVE,
    TASK_STATUS_CANCELLED,
    TASK_STATUS_DELETED
]

export default TaskStatusEnumArr

export {
    TASK_STATUS_PENDING,
    TASK_STATUS_INPROGRESS,
    TASK_STATUS_REVIEW,
    TASK_STATUS_COMPLETED,
    TASK_STATUS_ONLEAVE,
    TASK_STATUS_CANCELLED,
    TASK_STATUS_DELETED,
}