const PROJECT_STATUS_PENDING = 0
const PROJECT_STATUS_INPROGRESS = 1
const PROJECT_STATUS_REVIEW = 2
const PROJECT_STATUS_COMPLETED = 3
const PROJECT_STATUS_ONLEAVE = 4
const PROJECT_STATUS_CANCELLED = 5
const PROJECT_STATUS_DELETED = 6

const ProjectStatusEnum = {
    [PROJECT_STATUS_PENDING]: PROJECT_STATUS_PENDING,
    [PROJECT_STATUS_INPROGRESS]: PROJECT_STATUS_INPROGRESS,
    [PROJECT_STATUS_REVIEW]: PROJECT_STATUS_REVIEW,
    [PROJECT_STATUS_COMPLETED]: PROJECT_STATUS_COMPLETED,
    [PROJECT_STATUS_ONLEAVE]: PROJECT_STATUS_ONLEAVE,
    [PROJECT_STATUS_CANCELLED]: PROJECT_STATUS_CANCELLED,
    [PROJECT_STATUS_DELETED]: PROJECT_STATUS_DELETED,
}

const ProjectStatusEnumArr = [
    PROJECT_STATUS_PENDING,
    PROJECT_STATUS_INPROGRESS,
    PROJECT_STATUS_REVIEW,
    PROJECT_STATUS_COMPLETED,
    PROJECT_STATUS_ONLEAVE,
    PROJECT_STATUS_CANCELLED,
    PROJECT_STATUS_DELETED
]

export default ProjectStatusEnumArr

export {
    PROJECT_STATUS_PENDING,
    PROJECT_STATUS_INPROGRESS,
    PROJECT_STATUS_REVIEW,
    PROJECT_STATUS_COMPLETED,
    PROJECT_STATUS_ONLEAVE,
    PROJECT_STATUS_CANCELLED,
    PROJECT_STATUS_DELETED,
}