const PROJECT_MEMBER_TYPE_OWNER = 0
const PROJECT_MEMBER_TYPE_MANAGER = 1
const PROJECT_MEMBER_TYPE_LEADER = 2
const PROJECT_MEMBER_TYPE_ANALYST = 3
const PROJECT_MEMBER_TYPE_MEMBER = 4

const ProjectMemberTypeEnumArr = [
    PROJECT_MEMBER_TYPE_OWNER,
    PROJECT_MEMBER_TYPE_MANAGER,
    PROJECT_MEMBER_TYPE_LEADER,
    PROJECT_MEMBER_TYPE_ANALYST,
    PROJECT_MEMBER_TYPE_MEMBER,
]

export default ProjectMemberTypeEnumArr

export {
    PROJECT_MEMBER_TYPE_OWNER,
    PROJECT_MEMBER_TYPE_MANAGER,
    PROJECT_MEMBER_TYPE_LEADER,
    PROJECT_MEMBER_TYPE_ANALYST,
    PROJECT_MEMBER_TYPE_MEMBER,
}